[keys]
  [keys.normal]
  h = "move_left"
  j = "move_down"
  k = "move_up"
  l = "move_right"
  s = "save"
  i = "insert_mode"
  ESC = "quit"
  ARROW_UP = "move_up"
  ARROW_DOWN = "arrow_down"
  ARROW_LEFT = "arrow_left"
  ARROW_RIGHT = "arrow_right"

  [keys.insert]
  ESC = "normal_mode"
  BACKSPACE = "backspace"
  ENTER = "split_line"
  ARROW_UP = "move_up"
  ARROW_DOWN = "arrow_down"
  ARROW_LEFT = "arrow_left"
  ARROW_RIGHT = "arrow_right"
